### ISSUE TITLE
possibility for external Websites to create an QR Code automatically

### ISSUE THREAD

**Issue by gerhardbeck** [corona-warn-app/cwa-event-qr-code#11]
## Current Implementation

an batch creation (https://github.com/corona-warn-app/cwa-event-qr-code/issues/2)  is planned. But there is no way for external websites to create an QR Code automatically on their site

## Suggested Enhancement

My parish is using www.evangelische-termine.de as a calender. It would be great, if there would be a possibility for calendar/planning sites to offer a CWA QR-Code for each date. The necessary data is already existing.

## Expected Benefits
It would make it much easier for external sites to use the CWA QR Code

**Comment by mlenkeit** [comment]
Hi @gerhardbeck, thanks for opening the issue! Do you already have a specific proposal in mind on how to solve this? Such as generating QR codes from iCal? Or is it more like a general idea/suggestion?

**Comment by klaustopher** [comment]
The code to generate a QR code is included in the repository here. If the provider of your calendar wants to offer the QR code, couldn't they just re-implemented the code in their own backend or just use the provided NPM package here to generate a QR code for each event? There's no communication needed with any CWA servers to "register" an event.

**Comment by gerhardbeck** [comment]
@mlenkeit it's more a general suggestion, my technical knowlege is not good enough for suggestions

@klaustopher as far as I heard (didn't have direct contact yet), they already talked to someone and it seems very complicated to implement it. Which is sad as thousands of church parishes are using the system.

**Comment by mlenkeit** [comment]
@gerhardbeck this tool's primary use case is not so much for generating QR codes on a website, rather for automatically generating QR codes and then distributing them (e.g. central IT department of a company, etc.).

Generating QR codes on a website is already available under https://www.coronawarn.app/en/eventregistration/ and contributed by the community in https://github.com/corona-warn-app/cwa-website/pull/1132. Maybe it's worth passing this on to the people who run your website and calendar. Integrating that shouldn't be too complicated if they are familiar with JavaScript.

If they get stuck, they can always as for help here.

**Comment by gerhardbeck** [comment]
I'm already in contact with them. Thanks for the help.
