### ISSUE TITLE
Start time can be after end time

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-event-qr-code#7]
## Describe the bug

You can create an qr code with the start date after the end date.

## Expected behaviour

Throw an error

## Technical details

- Host Machine OS (Windows/Linux/Mac): macOS 11.2.3 Safari & Firefox 87

**Comment by mlenkeit** [comment]
You're right, there's generally no validation of the input fields yet.

**Comment by jucktnich** [comment]
There's a input validation, if the format fits, so there only has to be a check if endtime<starttime and if true, the same could appear.

**Comment by mlenkeit** [comment]
This is now fixed with the release of `1.2.0`
